all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 100.52.9.177
          ansible_private_key_file: ~/.ssh/connection_key.pem
        web2:
          ansible_host: 52.73.68.11
          ansible_private_key_file: ~/.ssh/public_vpc.pem
      vars:
        ansible_user: ubuntu